# Image aliases.
#
# Replace these placeholders with real files as your art comes in.

image bg_village_path_night = Solid("#080a0d")
image bg_village_road_night = Solid("#050608")
image bg_village_path_night_2 = Solid("#090b0f")
image bg_village_path_dawn = Solid("#2a3034")
image bg_car_interior_night = Solid("#0b0d10")
image bg_village_path_day = Solid("#59665b")
image bg_village_house_ext = Solid("#4f5a50")
image bg_village_centre = Solid("#626257")
image bg_fight_site = Solid("#1e2920")
image bg_burial_ground = Solid("#30352f")
image bg_family_house_ext = Solid("#3b342c")
image bg_family_house_int = Solid("#241f1a")
image bg_road_leaving = Solid("#252b24")
image bg_mc_city_apartment = Solid("#303239")
image bg_petrol_station = Solid("#4a4a42")
image bg_nayan_house_inside = Solid("#101010")
image bg_old_restaurant_day = Solid("#2a2118")
image bg_old_restaurant_evening = Solid("#241811")

image spr_mc neutral = Placeholder("boy")
image spr_mc listening = Placeholder("boy")
image spr_mc thinking = Placeholder("boy")
image spr_mc alert = Placeholder("boy")
image spr_mc focused = Placeholder("boy")
image spr_mc determined = Placeholder("boy")
image spr_mc shaken = Placeholder("boy")
image spr_mc injured = Placeholder("boy")
image spr_mc deaf = Placeholder("boy")
image spr_mc still = Placeholder("boy")
image spr_nayan neutral = Placeholder("boy")
image spr_nayan nervous = Placeholder("boy")
image spr_nayan terrified = Placeholder("boy")
image spr_hafiz neutral = Placeholder("boy")
image spr_hafiz amused = Placeholder("boy")
image spr_hafiz curious = Placeholder("boy")
image spr_hafiz serious = Placeholder("boy")
image spr_hafiz concerned = Placeholder("boy")
image spr_owner neutral = Placeholder("boy")
image spr_owner serious = Placeholder("boy")
image spr_owner distant = Placeholder("boy")
image spr_villager_1 terrified = Placeholder("boy")
image spr_villager_1 shocked = Placeholder("boy")
image spr_mak_ros nervous = Placeholder("girl")
image spr_mak_ros serious = Placeholder("girl")
image spr_mak_ros sad = Placeholder("girl")
image spr_villager_a neutral = Placeholder("boy")
image spr_villager_a nervous = Placeholder("boy")
image spr_son hostile = Placeholder("boy")
image spr_son warning = Placeholder("boy")
image spr_son cold = Placeholder("boy")
image spr_mother neutral = Placeholder("girl")
image spr_mother distant = Placeholder("girl")
image spr_mother speaking = Placeholder("girl")
image spr_mother grieving = Placeholder("girl")
image spr_pocong present = Placeholder("boy")
image spr_pocong attacking = Placeholder("boy")
image spr_pocong retreating = Placeholder("boy")
image spr_pocong stilled = Placeholder("boy")
image effect_flash_white = Solid("#ffffff")

define flash = Fade(0.1, 0.0, 0.3, color="#ffffff")
